FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y curl build-essential libssl-dev

RUN mkdir /rust
WORKDIR /rust
RUN curl -O https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
RUN tar xzvf rust-nightly-x86_64-unknown-linux-gnu.tar.gz --strip-components=1 -C /rust
RUN rm -f /rust/rust-nightly-x86_64-unknown-linux-gnu.tar.gz

ENV LD_LIBRARY_PATH /rust/rustc/lib
ENV PATH $PATH:/rust/cargo/bin:/rust/rustc/bin
ENV USER root

WORKDIR /code
